# Generated by Django 4.0.6 on 2022-07-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=100, null=True)),
                ('background', models.CharField(blank=True, max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('reply_rate', models.IntegerField(blank=True, null=True)),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('certification', models.IntegerField(blank=True, default=0, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_email_open', models.IntegerField(blank=True, default=1, null=True)),
                ('is_phone_open', models.IntegerField(blank=True, default=1, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
