# Generated by Django 4.0.6 on 2022-08-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='profile/person.png', null=True, upload_to='profile/'),
        ),
    ]
