# Generated by Django 4.0.6 on 2022-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_report',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
