# Generated by Django 4.0.6 on 2022-08-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
