# Generated by Django 4.0.6 on 2022-08-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='May I', max_length=20, null=True),
        ),
    ]
