# Generated by Django 4.0.6 on 2022-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reply_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
