# Generated by Django 4.0.6 on 2022-07-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('check_date', models.DateTimeField()),
                ('response', models.IntegerField(blank=True, default=0, null=True)),
                ('hold_reason', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=500)),
                ('deadline', models.DateTimeField()),
                ('is_send', models.IntegerField(blank=True, default=0, null=True)),
                ('is_expired', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
