# Generated by Django 4.0.6 on 2022-08-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='interview',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.interview'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='check_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='send_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
