# Generated by Django 4.0.6 on 2022-08-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
