# Generated by Django 4.0.6 on 2022-08-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_apply_expert_user_interview_reporter_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='expert_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='expert_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
