# Generated by Django 4.0.6 on 2022-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_amount_interview_file_interview_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
