# Generated by Django 4.0.6 on 2022-08-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_apply_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
